[2025-05-07 09:53:29] ERROR - Test Failed: placeOrderLoginBeforeCheckout - com.JodaynDemo.tests.TC16_OrderPlaceLoginBeforeCheckout
[2025-05-07 09:53:29] ERROR - Error: java.lang.AssertionError: Verify 'Logged in as username' at top expected [BilalTest1994] but found [[Logged in as Logged in as BilalTest1994]
[2025-05-07 09:53:29] ERROR - org.testng.Assert.fail(Assert.java:111)
[2025-05-07 09:53:29] ERROR - org.testng.Assert.failNotEquals(Assert.java:1590)
[2025-05-07 09:53:29] ERROR - org.testng.Assert.assertEqualsImpl(Assert.java:150)
[2025-05-07 09:53:29] ERROR - org.testng.Assert.assertEquals(Assert.java:132)
[2025-05-07 09:53:29] ERROR - org.testng.Assert.assertEquals(Assert.java:656)
[2025-05-07 09:53:29] ERROR - com.JodaynDemo.tests.TC16_OrderPlaceLoginBeforeCheckout.verifyLoggedInAsUsernameAtTop(TC16_OrderPlaceLoginBeforeCheckout.java:54)
[2025-05-07 09:53:29] ERROR - com.JodaynDemo.tests.TC16_OrderPlaceLoginBeforeCheckout.placeOrderLoginBeforeCheckout(TC16_OrderPlaceLoginBeforeCheckout.java:42)
[2025-05-07 09:53:29] ERROR - java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2025-05-07 09:53:29] ERROR - java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
[2025-05-07 09:53:29] ERROR - org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
[2025-05-07 09:53:29] ERROR - java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2025-05-07 09:53:29] ERROR - java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2025-05-07 09:53:29] ERROR - org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
[2025-05-07 09:53:29] ERROR - java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2025-05-07 09:53:29] ERROR - java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2025-05-07 09:53:29] ERROR - java.base/java.lang.Thread.run(Thread.java:1583)
